#!/usr/bin/env python3
"""
Kiểm tra conflicts với config hiện có trong project.
Xác định vùng an toàn để ghi và files cần merge.
"""

from pathlib import Path

MANAGED_START = "<!-- workflow-ai:start -->"
MANAGED_END = "<!-- workflow-ai:end -->"

MANAGED_FILES = [
    "scripts/gemini.py",
]


def detect_conflicts(project_root: str) -> dict:
    root = Path(project_root)

    return {
        "claude_md": _check_claude_md(root),
        "scripts_gemini": _check_file(root, "scripts/gemini.py"),
        "gitignore": _check_gitignore(root),
        "existing_configs": _list_existing_configs(root),
    }


# ── CLAUDE.md ────────────────────────────────────────────────────────────────

def _check_claude_md(root: Path) -> dict:
    path = root / "CLAUDE.md"
    if not path.exists():
        return {"status": "missing", "action": "create"}

    content = path.read_text()
    if MANAGED_START in content and MANAGED_END in content:
        return {
            "status": "managed",
            "action": "update_managed_section",
            "has_custom_content": _has_custom_content(content),
        }

    return {
        "status": "exists_unmanaged",
        "action": "append",
        "size_lines": len(content.splitlines()),
    }


def _has_custom_content(content: str) -> bool:
    """Kiểm tra có nội dung ngoài managed section không."""
    before = content.split(MANAGED_START)[0].strip()
    after = content.split(MANAGED_END)[-1].strip()
    return bool(before or after)


# ── scripts/gemini.py ────────────────────────────────────────────────────────

def _check_file(root: Path, relative_path: str) -> dict:
    path = root / relative_path
    if not path.exists():
        return {"status": "missing", "action": "create"}

    content = path.read_text()
    if "workflow-ai" in content or "Generated by workflow-ai" in content:
        return {"status": "managed", "action": "overwrite"}

    return {"status": "exists_unmanaged", "action": "skip_with_warning"}


# ── .gitignore ───────────────────────────────────────────────────────────────

def _check_gitignore(root: Path) -> dict:
    path = root / ".gitignore"
    if not path.exists():
        return {"status": "missing", "action": "create"}

    content = path.read_text()
    entries_needed = [".env", "*.pyc", "__pycache__/"]
    missing = [e for e in entries_needed if e not in content]

    return {
        "status": "exists",
        "action": "append_missing" if missing else "ok",
        "missing_entries": missing,
    }


# ── Existing configs ─────────────────────────────────────────────────────────

def _list_existing_configs(root: Path) -> list[str]:
    """List các config files quan trọng đã có — để báo cáo cho AI biết khi sinh CLAUDE.md."""
    known_configs = [
        "CLAUDE.md", ".env", ".env.example",
        "docker-compose.yml", "docker-compose.yaml", "Dockerfile",
        ".github/workflows", ".gitlab-ci.yml",
        "Makefile", "justfile",
        "tsconfig.json", "jsconfig.json",
        ".eslintrc", ".eslintrc.json", ".eslintrc.js",
        ".prettierrc", ".prettierrc.json",
        "pyproject.toml", "setup.cfg", "mypy.ini", ".flake8",
        ".rubocop.yml",
        ".golangci.yml",
    ]
    return [c for c in known_configs if (root / c).exists()]


# ── Apply helpers (dùng bởi install.py) ─────────────────────────────────────

def write_managed_section(file_path: Path, content: str):
    """Ghi hoặc update managed section trong file."""
    managed_block = f"\n{MANAGED_START}\n{content.strip()}\n{MANAGED_END}\n"

    if not file_path.exists():
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(managed_block.lstrip())
        return

    existing = file_path.read_text()

    if MANAGED_START in existing and MANAGED_END in existing:
        # Replace existing managed section
        before = existing.split(MANAGED_START)[0]
        after = existing.split(MANAGED_END)[-1]
        file_path.write_text(before + managed_block + after)
    else:
        # Append managed section
        file_path.write_text(existing.rstrip() + managed_block)


def append_gitignore_entries(root: Path, entries: list[str]):
    path = root / ".gitignore"
    existing = path.read_text() if path.exists() else ""
    to_add = [e for e in entries if e not in existing]
    if to_add:
        block = "\n# workflow-ai\n" + "\n".join(to_add) + "\n"
        with path.open("a") as f:
            f.write(block)


if __name__ == "__main__":
    import sys
    import pprint
    path = sys.argv[1] if len(sys.argv) > 1 else "."
    pprint.pprint(detect_conflicts(path))
