#!/usr/bin/env python3
"""
Script để Claude Code gọi Gemini API sinh code.
Generated by workflow-ai — https://github.com/your-username/workflow-ai

Yêu cầu: pip install google-genai>=1.0
Dùng:    python scripts/gemini.py "prompt" [file1] [file2] ...
Env:     Đặt GEMINI_API_KEY trong .env ở thư mục gốc dự án
         GEMINI_MODEL=gemini-2.5-flash  (mặc định: gemini-2.5-pro)
"""

import re
import sys
import os
import time
from pathlib import Path
from google import genai

def _load_env():
    """Load .env từ thư mục chứa script này (gốc dự án), không ghi đè env var đã có."""
    env_path = Path(__file__).parent.parent / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:  # không ghi đè shell export
            os.environ[key] = value

_load_env()

MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-pro")
MAX_RETRIES = 3
RETRY_DELAY = 10  # seconds

SYSTEM_PROMPT = """Bạn là code generator chuyên nghiệp. Quy tắc bắt buộc:
- Chỉ xuất code, không có giải thích hay commentary thừa
- Không bọc output trong markdown code fence (```)
- Mỗi file bắt đầu bằng comment: // Generated by Gemini — cần review trước khi dùng
- Tuân thủ conventions của dự án nếu được cung cấp trong context
"""


def strip_markdown_fence(text: str) -> str:
    """Xóa markdown code fence mà Gemini thường thêm vào."""
    text = text.strip()
    text = re.sub(r"^```[^\n]*\n", "", text)
    text = re.sub(r"\n```$", "", text)
    return text


def call_gemini(prompt: str, context_files: list[str] = None) -> str:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise EnvironmentError("GEMINI_API_KEY chưa được set. Chạy: export GEMINI_API_KEY=xxx")

    base_url = os.environ.get("GEMINI_BASE_URL")
    if base_url:
        print(f"[gemini.py] Dùng proxy: {base_url}", file=sys.stderr)
        client = genai.Client(api_key=api_key, http_options={"base_url": base_url})
    else:
        client = genai.Client(api_key=api_key)

    # Build full prompt với context files
    full_prompt = SYSTEM_PROMPT + "\n\n"

    if context_files:
        for f in context_files:
            try:
                with open(f) as fh:
                    full_prompt += f"\n--- {f} ---\n{fh.read()}\n"
            except FileNotFoundError:
                print(f"[gemini.py] CẢNH BÁO: Không tìm thấy file '{f}', bỏ qua.", file=sys.stderr)

    full_prompt += f"\n--- NHIỆM VỤ ---\n{prompt}"

    # Gọi API với retry
    last_error = None
    for attempt in range(MAX_RETRIES):
        try:
            response = client.models.generate_content(
                model=MODEL,
                contents=full_prompt,
            )
            return strip_markdown_fence(response.text)
        except Exception as e:
            last_error = e
            if attempt < MAX_RETRIES - 1:
                wait = RETRY_DELAY * (attempt + 1)
                print(f"[gemini.py] Lỗi (attempt {attempt + 1}/{MAX_RETRIES}): {e}. Retry sau {wait}s...",
                      file=sys.stderr)
                time.sleep(wait)

    raise RuntimeError(f"Gemini API thất bại sau {MAX_RETRIES} lần thử: {last_error}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Dùng: python scripts/gemini.py \"prompt\" [file1] [file2] ...", file=sys.stderr)
        print(f"      GEMINI_MODEL={MODEL} (mặc định)", file=sys.stderr)
        sys.exit(1)

    try:
        prompt = sys.argv[1]
        files = sys.argv[2:] if len(sys.argv) > 2 else []
        print(call_gemini(prompt, files))
    except Exception as e:
        print(f"GEMINI_ERROR: {e}", file=sys.stderr)
        sys.exit(1)
